"""Lambda 2 entry point for the AI Radar AWS Website Builder Pipeline.

This handler is invoked asynchronously by Lambda 1 after the report generation
pipeline completes. It builds the static website from CSV data in S3, uploads
files to the website S3 bucket using a staged approach (temp prefix first, then
copy to final location), and invalidates the CloudFront cache.

On failure, existing site files are preserved — no partial uploads reach the
live site.
"""

import os
import uuid

import boto3

from src.config import Config
from src.shared.logger import StructuredLogger
from src.website_builder.builder import WebsiteBuilder


def handler(event: dict, context) -> dict:
    """Lambda 2 handler — Website Builder Pipeline.

    Args:
        event: The invocation payload from Lambda 1 containing run_id.
        context: The Lambda execution context.

    Returns:
        A dict with statusCode and summary of the website build.
    """
    # Extract run_id from Lambda 1 payload for correlated logging
    run_id = event.get("run_id", str(uuid.uuid4()))

    # Initialize configuration and structured logger
    config = Config()
    logger = StructuredLogger(lambda_name="website-builder", run_id=run_id)

    logger.info(
        "Lambda 2 handler invoked",
        source=event.get("source", "unknown"),
    )

    # Read environment variables for bucket names and CloudFront distribution
    data_bucket = os.environ.get("DATA_BUCKET_NAME", "")
    website_bucket = os.environ.get("WEBSITE_BUCKET_NAME", "")
    distribution_id = os.environ.get("CLOUDFRONT_DISTRIBUTION_ID", "")

    if not data_bucket or not website_bucket:
        logger.error(
            "Missing required environment variables",
            data_bucket_set=bool(data_bucket),
            website_bucket_set=bool(website_bucket),
        )
        return {
            "statusCode": 500,
            "body": {
                "run_id": run_id,
                "error": "Missing required environment variables (DATA_BUCKET_NAME, WEBSITE_BUCKET_NAME)",
            },
        }

    try:
        s3_client = boto3.client("s3", region_name=config.aws_region)
        cloudfront_client = boto3.client("cloudfront", region_name=config.aws_region)

        # Build the website files
        builder = WebsiteBuilder(
            config=config,
            s3_client=s3_client,
            logger=logger,
            data_bucket=data_bucket,
        )
        files = builder.build_and_get_files()

        if not files:
            logger.warning("No files generated by website builder")
            return {
                "statusCode": 200,
                "body": {
                    "run_id": run_id,
                    "files_uploaded": 0,
                    "message": "No files generated (possibly no announcements in CSV)",
                },
            }

        # Upload files using staged approach to prevent partial uploads
        _staged_upload(
            s3_client=s3_client,
            logger=logger,
            bucket=website_bucket,
            files=files,
        )

        # Invalidate CloudFront cache
        if distribution_id:
            _invalidate_cloudfront(
                cloudfront_client=cloudfront_client,
                logger=logger,
                distribution_id=distribution_id,
            )
        else:
            logger.warning(
                "CLOUDFRONT_DISTRIBUTION_ID not set, skipping cache invalidation"
            )

        logger.info(
            "Website build and deploy completed successfully",
            files_uploaded=len(files),
        )

        return {
            "statusCode": 200,
            "body": {
                "run_id": run_id,
                "files_uploaded": len(files),
            },
        }

    except Exception as exc:
        logger.error(
            "Website build failed — existing site preserved",
            error_type=type(exc).__name__,
            error_message=str(exc),
        )
        return {
            "statusCode": 500,
            "body": {
                "run_id": run_id,
                "error": str(exc),
            },
        }


def _staged_upload(
    s3_client,
    logger: StructuredLogger,
    bucket: str,
    files: dict[str, str],
) -> None:
    """Upload files using a staged approach to prevent partial uploads.

    Strategy:
    1. Upload all files to a temporary prefix (_staging/)
    2. Once all staging uploads succeed, copy each file to its final location
    3. Clean up the staging prefix

    If any staging upload fails, the exception propagates and existing site
    files remain untouched.
    """
    staging_prefix = "_staging/"

    logger.info("Starting staged upload", total_files=len(files))

    # Stage 1: Upload all files to staging prefix
    for file_path, content in files.items():
        staging_key = f"{staging_prefix}{file_path}"
        content_type = _get_content_type(file_path)

        try:
            s3_client.put_object(
                Bucket=bucket,
                Key=staging_key,
                Body=content.encode("utf-8"),
                ContentType=content_type,
                ServerSideEncryption="AES256",
            )
        except Exception as exc:
            logger.error(
                "Staging upload failed — aborting, existing site preserved",
                file_path=file_path,
                error_type=type(exc).__name__,
                error_message=str(exc),
            )
            # Attempt cleanup of any staged files
            _cleanup_staging(s3_client, bucket, staging_prefix, logger)
            raise

    logger.info("All files staged successfully, copying to final location")

    # Stage 2: Copy from staging to final location
    for file_path in files:
        staging_key = f"{staging_prefix}{file_path}"
        try:
            s3_client.copy_object(
                Bucket=bucket,
                Key=file_path,
                CopySource={"Bucket": bucket, "Key": staging_key},
                ContentType=_get_content_type(file_path),
                ServerSideEncryption="AES256",
                MetadataDirective="REPLACE",
            )
        except Exception as exc:
            logger.error(
                "Copy from staging failed",
                file_path=file_path,
                error_type=type(exc).__name__,
                error_message=str(exc),
            )
            # Don't cleanup staging on copy failure — files are already staged
            # and the site may be partially updated. Log and raise.
            raise

    # Stage 3: Clean up staging prefix
    _cleanup_staging(s3_client, bucket, staging_prefix, logger)

    logger.info("Staged upload completed successfully", files_deployed=len(files))


def _cleanup_staging(s3_client, bucket: str, prefix: str, logger: StructuredLogger) -> None:
    """Remove all objects under the staging prefix. Best-effort cleanup."""
    try:
        paginator = s3_client.get_paginator("list_objects_v2")
        pages = paginator.paginate(Bucket=bucket, Prefix=prefix)

        for page in pages:
            objects = page.get("Contents", [])
            if objects:
                delete_keys = [{"Key": obj["Key"]} for obj in objects]
                s3_client.delete_objects(
                    Bucket=bucket,
                    Delete={"Objects": delete_keys},
                )
    except Exception as exc:
        # Cleanup is best-effort — don't fail the overall operation
        logger.warning(
            "Staging cleanup failed (non-critical)",
            error_type=type(exc).__name__,
            error_message=str(exc),
        )


def _invalidate_cloudfront(
    cloudfront_client,
    logger: StructuredLogger,
    distribution_id: str,
) -> None:
    """Create a CloudFront invalidation for all paths (/*).

    Retries up to 2 times on failure with 1s delay.
    """
    import time

    caller_reference = str(uuid.uuid4())
    max_retries = 2

    for attempt in range(max_retries + 1):
        try:
            cloudfront_client.create_invalidation(
                DistributionId=distribution_id,
                InvalidationBatch={
                    "Paths": {
                        "Quantity": 1,
                        "Items": ["/*"],
                    },
                    "CallerReference": caller_reference,
                },
            )
            logger.info(
                "CloudFront invalidation created",
                distribution_id=distribution_id,
                caller_reference=caller_reference,
            )
            return
        except Exception as exc:
            if attempt < max_retries:
                logger.warning(
                    "CloudFront invalidation failed, retrying",
                    attempt=attempt + 1,
                    max_retries=max_retries,
                    error_type=type(exc).__name__,
                    error_message=str(exc),
                )
                time.sleep(1)
            else:
                logger.error(
                    "CloudFront invalidation failed after all retries",
                    distribution_id=distribution_id,
                    error_type=type(exc).__name__,
                    error_message=str(exc),
                )
                raise


def _get_content_type(file_path: str) -> str:
    """Determine the Content-Type for a file based on its extension."""
    extension = file_path.rsplit(".", 1)[-1].lower() if "." in file_path else ""
    content_types = {
        "html": "text/html; charset=utf-8",
        "css": "text/css; charset=utf-8",
        "js": "application/javascript; charset=utf-8",
        "json": "application/json; charset=utf-8",
        "svg": "image/svg+xml",
        "png": "image/png",
        "ico": "image/x-icon",
        "txt": "text/plain; charset=utf-8",
    }
    return content_types.get(extension, "application/octet-stream")
